name: isolate_executor_2
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
version: 1.0.0
homepage: https://github.com/stablekernel/dart-isolate-executor
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

# Change when IPR is resolved with Stable/Kernel
publish_to: none

dependencies:
  analyzer: ^0.41.1
  pub_semver: ^2.0.0

dev_dependencies:
  test: ^1.3.0
  test_package:
    path: test/test_package
